/**
 * worldmap - an extension to JMapViewer which provides additional
 *            functionality. New functions allow setting markers,
 *            adding layers, and printing tracks on the map. (see
 *            http://wiki.openstreetmap.org/wiki/JMapViewer for more
 *            information on JMapViewer)
 *
 * Copyright (c) 2011
 *
 * Fraunhofer FOKUS
 * www.fokus.fraunhofer.de
 *
 * in cooperation with
 *
 * Technical University Berlin
 * www.av.tu-berlin.de
 *
 * Ramon Masek <ramon.masek@fokus.fraunhofer.de>
 * Christian Henke <c.henke@tu-berlin.de>
 * Carsten Schmoll <carsten.schmoll@fokus.fraunhofer.de>
 * Julian Vetter <julian.vetter@fokus.fraunhofer.de>
 * Jens Krenzin <jens.krenzin@fokus.fraunhofer.de>
 * Michael Gehring <michael.gehring@fokus.fraunhofer.de>
 * Tacio Grespan Santos
 * Fabian Wolff
 *
 * For questions/comments contact packettracking@fokus.fraunhofer.de
 *
 * This program is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software Foundation;
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, see <http://www.gnu.org/licenses/>.
 */

package de.fhg.fokus.net.worldmap.layers.track;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Composite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JSlider;
import javax.swing.JToolBar;

/**
 *
 * @author FhG-FOKUS NETwork Research
 */
public class TrackPlayerPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private final Composite bgComposite = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f);
	private Color bgColor = new Color(200, 200, 200);

	@Override
	protected void paintComponent(Graphics g) {
		Graphics2D g2 = (Graphics2D)g;
		g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
		Composite oldComposite = g2.getComposite();

		g2.setComposite(bgComposite);
		g2.setColor(bgColor);
		g2.fillRoundRect(0,0, getWidth(), getHeight(), 10, 10);
		g2.setComposite(oldComposite);

	}

    /** Creates new form TrackPlayerPanel */
    public TrackPlayerPanel() {
        initComponents();
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarLeft = new javax.swing.JToolBar();
        jButtonStart = new javax.swing.JButton();
        jButtonPause = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jPanelStart = new javax.swing.JPanel();
        jLabelStartTime = new javax.swing.JLabel();
        jLabelStartDate = new javax.swing.JLabel();
        jPanelSlider = new javax.swing.JPanel();
        jSliderTime = new javax.swing.JSlider();
        jLabelCurrentTimestamp = new javax.swing.JLabel();
        jLabelResolution = new javax.swing.JLabel();
        jPanelStop = new javax.swing.JPanel();
        jLabelStopTime = new javax.swing.JLabel();
        jLabelStopDate = new javax.swing.JLabel();
        jSeparatorStopTime = new javax.swing.JSeparator();
        jPanelNumberOfTracks = new javax.swing.JPanel();
        jLabelNumberOfTracks = new javax.swing.JLabel();
        jLabelFitInterval = new javax.swing.JLabel();
        jPanelStatus = new javax.swing.JPanel();
        jSeparatorStopTime1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelReloadTracks = new javax.swing.JLabel();
        jToolBarRight = new javax.swing.JToolBar();
        jButtonSettings = new javax.swing.JButton();

        setOpaque(false);

        jToolBarLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBarLeft.setFloatable(false);
        jToolBarLeft.setRollover(true);

        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/fhg/fokus/net/worldmap/view/resources/media-playback-start.png"))); // NOI18N
        jButtonStart.setFocusable(false);
        jButtonStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarLeft.add(jButtonStart);

        jButtonPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/fhg/fokus/net/worldmap/view/resources/media-playback-pause.png"))); // NOI18N
        jButtonPause.setToolTipText("Pause");
        jButtonPause.setFocusable(false);
        jButtonPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarLeft.add(jButtonPause);

        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/fhg/fokus/net/worldmap/view/resources/media-playback-stop.png"))); // NOI18N
        jButtonStop.setToolTipText("Stop");
        jButtonStop.setFocusable(false);
        jButtonStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarLeft.add(jButtonStop);

        add(jToolBarLeft);

        jPanelStart.setOpaque(false);
        jPanelStart.setLayout(new java.awt.BorderLayout());

        jLabelStartTime.setFont(new java.awt.Font("DejaVu Sans", 1, 11));
        jLabelStartTime.setForeground(java.awt.Color.darkGray);
        jLabelStartTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStartTime.setText("00:00:00");
        jLabelStartTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelStartTime.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelStart.add(jLabelStartTime, java.awt.BorderLayout.NORTH);

        jLabelStartDate.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabelStartDate.setForeground(java.awt.Color.darkGray);
        jLabelStartDate.setText("2009-10-28");
        jLabelStartDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelStart.add(jLabelStartDate, java.awt.BorderLayout.SOUTH);

        add(jPanelStart);

        jPanelSlider.setOpaque(false);
        jPanelSlider.setLayout(new java.awt.BorderLayout());

        jSliderTime.setPreferredSize(new java.awt.Dimension(370, 37));
        jPanelSlider.add(jSliderTime, java.awt.BorderLayout.NORTH);

        jLabelCurrentTimestamp.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabelCurrentTimestamp.setForeground(java.awt.Color.darkGray);
        jLabelCurrentTimestamp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurrentTimestamp.setText("2009-10-28 00:00:00");
        jLabelCurrentTimestamp.setToolTipText("Current timestamp");
        jPanelSlider.add(jLabelCurrentTimestamp, java.awt.BorderLayout.CENTER);

        jLabelResolution.setFont(new java.awt.Font("DejaVu Sans", 1, 10));
        jLabelResolution.setForeground(java.awt.Color.gray);
        jLabelResolution.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResolution.setText("1000 ms");
        jLabelResolution.setToolTipText("Resolution");
        jPanelSlider.add(jLabelResolution, java.awt.BorderLayout.EAST);

        add(jPanelSlider);

        jPanelStop.setOpaque(false);
        jPanelStop.setLayout(new java.awt.BorderLayout());

        jLabelStopTime.setFont(new java.awt.Font("DejaVu Sans", 1, 11));
        jLabelStopTime.setForeground(java.awt.Color.darkGray);
        jLabelStopTime.setText("00:00:00");
        jLabelStopTime.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelStop.add(jLabelStopTime, java.awt.BorderLayout.NORTH);

        jLabelStopDate.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabelStopDate.setForeground(java.awt.Color.darkGray);
        jLabelStopDate.setText("2009-10-28");
        jLabelStopDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelStop.add(jLabelStopDate, java.awt.BorderLayout.SOUTH);

        add(jPanelStop);

        jSeparatorStopTime.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparatorStopTime.setPreferredSize(new java.awt.Dimension(10, 30));
        add(jSeparatorStopTime);

        jPanelNumberOfTracks.setOpaque(false);
        jPanelNumberOfTracks.setLayout(new java.awt.BorderLayout());

        jLabelNumberOfTracks.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabelNumberOfTracks.setForeground(java.awt.Color.darkGray);
        jLabelNumberOfTracks.setText("# 000 / 000");
        jLabelNumberOfTracks.setToolTipText("Number of Tracks (click to refresh)");
        jLabelNumberOfTracks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelNumberOfTracks.add(jLabelNumberOfTracks, java.awt.BorderLayout.NORTH);

        jLabelFitInterval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFitInterval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/fhg/fokus/net/worldmap/view/resources/fit.png"))); // NOI18N
        jLabelFitInterval.setToolTipText("Fit interval");
        jPanelNumberOfTracks.add(jLabelFitInterval, java.awt.BorderLayout.SOUTH);

        add(jPanelNumberOfTracks);

        jPanelStatus.setOpaque(false);
        jPanelStatus.setLayout(new java.awt.BorderLayout());
        add(jPanelStatus);

        jSeparatorStopTime1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparatorStopTime1.setPreferredSize(new java.awt.Dimension(10, 30));
        add(jSeparatorStopTime1);

        jPanel1.setOpaque(false);

        jLabelReloadTracks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReloadTracks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/fhg/fokus/net/worldmap/view/resources/database_refresh.png"))); // NOI18N
        jLabelReloadTracks.setToolTipText("Reload Tracks");
        jPanel1.add(jLabelReloadTracks);

        add(jPanel1);

        jToolBarRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBarRight.setFloatable(false);
        jToolBarRight.setRollover(true);
        jToolBarRight.setOpaque(false);

        jButtonSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/fhg/fokus/net/worldmap/view/resources/config2.png"))); // NOI18N
        jButtonSettings.setToolTipText("Settings");
        jButtonSettings.setEnabled(false);
        jButtonSettings.setFocusable(false);
        jButtonSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarRight.add(jButtonSettings);

        add(jToolBarRight);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabelCurrentTimestamp;
    private javax.swing.JLabel jLabelFitInterval;
    private javax.swing.JLabel jLabelNumberOfTracks;
    private javax.swing.JLabel jLabelReloadTracks;
    private javax.swing.JLabel jLabelResolution;
    private javax.swing.JLabel jLabelStartDate;
    private javax.swing.JLabel jLabelStartTime;
    private javax.swing.JLabel jLabelStopDate;
    private javax.swing.JLabel jLabelStopTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelNumberOfTracks;
    private javax.swing.JPanel jPanelSlider;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JPanel jPanelStop;
    private javax.swing.JSeparator jSeparatorStopTime;
    private javax.swing.JSeparator jSeparatorStopTime1;
    private javax.swing.JSlider jSliderTime;
    private javax.swing.JToolBar jToolBarLeft;
    private javax.swing.JToolBar jToolBarRight;
    // End of variables declaration//GEN-END:variables

   public Color getBgColor() {
      return bgColor;
   }

   public Composite getBgComposite() {
      return bgComposite;
   }

   public JButton getjButtonPause() {
      return jButtonPause;
   }

   public JButton getjButtonSettings() {
      return jButtonSettings;
   }

   public JButton getjButtonStart() {
      return jButtonStart;
   }

   public JButton getjButtonStop() {
      return jButtonStop;
   }

   public JLabel getjLabelStartTime() {
      return jLabelStartTime;
   }

   public JLabel getjLabelStartDate() {
      return jLabelStartDate;
   }

   public JLabel getjLabelStopTime() {
      return jLabelStopTime;
   }
   public JLabel getjLabelStopDate() {
      return jLabelStopDate;
   }


   public JSlider getjSliderTime() {
      return jSliderTime;
   }

   public JToolBar getjToolBarLeft() {
      return jToolBarLeft;
   }

   public JToolBar getjToolBarRight() {
      return jToolBarRight;
   }

   public JLabel getjLabelNumberOfTracks() {
      return jLabelNumberOfTracks;
   }

   public JLabel getjLabelReloadTracks() {
      return jLabelReloadTracks;
   }

   public JPanel getjPanelStart() {
      return jPanelStart;
   }

   public JPanel getjPanelStatus() {
      return jPanelStatus;
   }

   public JPanel getjPanelStop() {
      return jPanelStop;
   }

   public JSeparator getjSeparatorStopTime() {
      return jSeparatorStopTime;
   }

   public JLabel getjLabelCurrentTimestamp() {
      return jLabelCurrentTimestamp;
   }

   public JLabel getjLabelFitInterval() {
      return jLabelFitInterval;
   }

   public JLabel getjLabelResolution() {
      return jLabelResolution;
   }
   
}

